services:
  geth:
    image: ethereum/client-go:stable
    container_name: ethereum-execution
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - ethereum-net
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "6060:6060"
      - "8551:8551"
    volumes:
      - /External/ethereum/geth-data:/home/geth/.ethereum
      - /External/ethereum/jwt/jwt.hex:/home/geth/jwt.hex:ro
    environment:
      - HOME=/home/geth
    command:
      - --datadir=/home/geth/.ethereum
      - --syncmode=snap
      - --verbosity=4
      - --cache=4096
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain="*"
      - --http.vhosts=localhost,127.0.0.1,ethereum-execution,*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3,txpool
      - --maxpeers=50
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=localhost,127.0.0.1,ethereum-consensus,*
      - --authrpc.jwtsecret=/home/geth/jwt.hex
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --networkid=1

  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    container_name: ethereum-consensus
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - ethereum-net
    ports:
      - "13000:13000"
      - "13000:13000/udp"
      - "4000:4000"
      - "9000:9000/udp"
      - "8080:8080"
    volumes:
      - /External/ethereum/prysm-data:/home/prysm/.eth2
      - /External/ethereum/jwt/jwt.hex:/home/prysm/jwt.hex:ro
    environment:
      - HOME=/home/prysm
    command:
      - --accept-terms-of-use=true
      - --datadir=/home/prysm/.eth2
      - --execution-endpoint=http://ethereum-execution:8551
      - --jwt-secret=/home/prysm/jwt.hex
      - --mainnet=true
      - --checkpoint-sync-url=https://beaconstate.ethstaker.cc
      - --genesis-beacon-api-url=https://beaconstate.ethstaker.cc
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --monitoring-port=8080
      - --p2p-tcp-port=13000
      - --p2p-udp-port=13000
      - --suggested-fee-recipient=0x742d35Cc6634C0532925a3b844Bc454e4438f44e
      - --p2p-host-dns=${DYNDNS}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - ethereum-net
    ports:
      - "3000:3000"
    volumes:
      - /External/ethereum/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: root
    networks:
      - ethereum-net
    ports:
      - "9090:9090"
    volumes:
      - /External/ethereum/prometheus:/prometheus
      - /External/ethereum/prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

networks:
  ethereum-net:
    driver: bridge